name: CI Linux Mac

on:
  push:
    branches:
      - main
      - master
    tags-ignore:
      - '*'
    paths-ignore: 
      - README.md
      - LICENSE
      - docs/*

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Test
      run: |
        .sdlc/build
        .sdlc/check
